### ISSUE TITLE
Recent containers haven't been pushed to Galaxy Singularity registry

### ISSUE THREAD

**Issue by drpatelh** [BioContainers/singularity-build-bot#3]
Hi! I have noticed that a few tools that have been updated on Bioconda have had their images created on Quay.io as expected but the corresponding Singularity image doesn't yet exist on https://depot.galaxyproject.org/singularity  

For example, the latest version of Pangolin (`2.4.2--pyhdfd78af_0`) is available on [Quay.io](https://quay.io/repository/biocontainers/pangolin?tab=tags) but returns a `404` if you click on the [Galaxy link](https://depot.galaxyproject.org/singularity/pangolin:2.4.2--pyhdfd78af_0). 

Similarly, the latest version of MultiQC (`1.10.1--pyhdfd78af_1`) isn't available via the [Galaxy link](https://depot.galaxyproject.org/singularity/multiqc:1.10.1--pyhdfd78af_1) either.

Not sure if this is expected or not but thought I would report it here just in case :)

**Comment by simonbray** [comment]
Hi @drpatelh,

The bot CI broke last week, meaning that the new containers were not being created. It should be fixed now (those two links you provided are no longer returning 404s).

Thanks a lot for reporting!

Simon

**Comment by drpatelh** [comment]
Awesome! Thank you @simonbray :)
