### ISSUE TITLE
HTSLIB Container not available in singularity

### ISSUE THREAD

**Issue by FriederikeHanssen** [BioContainers/singularity-build-bot#4]
Hi! I wanted to use the htslib container, which I found available at quay.io [here]( https://quay.io/repository/biocontainers/htslib?tag=latest&tab=tags ), but couldn't find the corresponding singularity images [here]( https://depot.galaxyproject.org/singularity).

I was just wondering, if this could be added or whether there is a reason it is not there :)

**Comment by simonbray** [comment]
Hi @FriederikeHanssen, it is on our skiplist of containers which should not be built: https://github.com/BioContainers/singularity-build-bot/blob/master/skip.list

I am not sure of the reason. Maybe @bgruening has an idea.

**Comment by bgruening** [comment]
Oh, no particular reason, I think I thought "its a lib, who needs a container for it" ;) but obviously, I was wrong. Please remove it from the skiplist.

**Comment by FriederikeHanssen** [comment]
Awesome 🎉  Thank you @simonbray and @bgruening !

**Comment by simonbray** [comment]
Hi @FriederikeHanssen, I removed htslib from the skiplist and the new singularity containers have now been built.
